"""empty message

Revision ID: 05bba96e6a4c
Revises: None
Create Date: 2016-02-23 17:41:23.953190

"""

# revision identifiers, used by Alembic.
revision = '05bba96e6a4c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('jobposter', sa.Boolean(), nullable=True),
    sa.Column('suggester', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('paypalemail', sa.String(length=140), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('totalwinnings', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('anything_else', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('winner', sa.String(length=140), nullable=True),
    sa.Column('project_type', sa.String(length=140), nullable=True),
    sa.Column('number_of_entries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Suggest1', sa.String(length=140), nullable=True),
    sa.Column('Suggest2', sa.String(length=140), nullable=True),
    sa.Column('Suggest3', sa.String(length=140), nullable=True),
    sa.Column('Suggest4', sa.String(length=140), nullable=True),
    sa.Column('Suggest5', sa.String(length=140), nullable=True),
    sa.Column('suggester', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('winstatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['posting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    op.drop_table('posting')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
