"""empty message

Revision ID: 595c76958974
Revises: e579fa452c03
Create Date: 2016-02-20 17:25:50.391101

"""

# revision identifiers, used by Alembic.
revision = '595c76958974'
down_revision = 'e579fa452c03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('number_of_entries', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'number_of_entries')
    ### end Alembic commands ###
