"""empty message

Revision ID: 67373b1a981a
Revises: efe6967d5b70
Create Date: 2016-03-12 19:46:34.958834

"""

# revision identifiers, used by Alembic.
revision = '67373b1a981a'
down_revision = 'efe6967d5b70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
