"""empty message

Revision ID: 925b00d2e086
Revises: 7eef1dbad78e
Create Date: 2016-03-28 09:16:39.988704

"""

# revision identifiers, used by Alembic.
revision = '925b00d2e086'
down_revision = '7eef1dbad78e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paydue', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'paydue')
    ### end Alembic commands ###
