"""empty message

Revision ID: b390cac2e1bf
Revises: 865e69dc3f9f
Create Date: 2016-02-29 14:43:09.909783

"""

# revision identifiers, used by Alembic.
revision = 'b390cac2e1bf'
down_revision = '865e69dc3f9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('timestamp_day', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'timestamp_day')
    ### end Alembic commands ###
