"""empty message

Revision ID: d9eda39184f3
Revises: b390cac2e1bf
Create Date: 2016-03-08 11:46:51.148407

"""

# revision identifiers, used by Alembic.
revision = 'd9eda39184f3'
down_revision = 'b390cac2e1bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emailnotes', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emailnotes')
    ### end Alembic commands ###
