"""empty message

Revision ID: e579fa452c03
Revises: 1e6e2734ee2d
Create Date: 2016-02-16 11:45:45.035927

"""

# revision identifiers, used by Alembic.
revision = 'e579fa452c03'
down_revision = '1e6e2734ee2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('project_type', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'project_type')
    ### end Alembic commands ###
