"""empty message

Revision ID: efe6967d5b70
Revises: d9eda39184f3
Create Date: 2016-03-08 19:42:38.085120

"""

# revision identifiers, used by Alembic.
revision = 'efe6967d5b70'
down_revision = 'd9eda39184f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('project_prize', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posting', 'project_prize')
    ### end Alembic commands ###
